trigger: none

resources:
  pipelines:
  - pipeline: validation
    source: Nabanita-Sahu.Validate
    project: PipelineDemo
    branch: main
    trigger: true

pool:
  name: DevOpsPracticePool

stages:
- stage: Deploy
  displayName: "Deploy Stage"
  jobs:
  - job: DeployJob
    displayName: "Deploy Application"
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: "Download build artifacts"
        inputs:
          source: specific
          project: PipelineDemo
          pipeline: Nabanita-Sahu.Validate
          runVersion: latest
          artifact: drop
          path: $(Agent.WorkFolder)\drop     #  Correct path for Windows self‑hosted agent

      - script: |
          echo Starting deployment...

          echo Agent.WorkFolder = $(Agent.WorkFolder)
          dir "$(Agent.WorkFolder)"

          echo Listing drop folder contents (if exists):
          dir "$(Agent.WorkFolder)\drop"

          set "ARTIFACT_PATH=$(Agent.WorkFolder)\drop"

          echo Checking for artifact at: %ARTIFACT_PATH%

          if exist "%ARTIFACT_PATH%" (
            echo Artifact 'drop' found at: %ARTIFACT_PATH%
            echo Deploying application...
            REM CORRECTED: Use REM instead of :: inside blocks
            REM Add your deployment command below (e.g., copy, unzip)
            
          ) else (
            echo Artifact 'drop' not found. Deployment cannot continue.
            exit /b 1
          )
        displayName: "Deployment Step"