trigger: none   # Do not run on code push

resources:
  pipelines:
  - pipeline: validation
    source: Nabanita-Sahu.Validate   # Exact name of your validation pipeline
    trigger: true                    # ✅ Auto-run deploy after validation succeeds

pool:
  name: DevOpsPracticePool

stages:
- stage: Deploy
  displayName: "Deploy Stage"
  jobs:
  - job: DeployJob
    displayName: "Deploy Application"
    steps:

    # ✅ Download artifact from the validation run that triggered this pipeline
    - task: DownloadPipelineArtifact@2
      displayName: "Download build artifacts"
      inputs:
        source: current              # ✅ Use the triggering pipeline run
        artifact: drop               # ✅ Must match the artifact name from validation
        path: $(Pipeline.Workspace)

    - script: |
        echo "Deploying application..."
        echo "Artifacts downloaded to $(Pipeline.Workspace)"
      displayName: "Deployment Step"