trigger: none   # Deployment should not run automatically on code push

resources:
  pipelines:
  - pipeline: validation
    source: Nabanita-Sahu.Validate   # ✅ EXACT name of your validate pipeline
    trigger: true                    # ✅ Auto-run deploy after validate succeeds

pool:
  name: DevOpsPracticePool

stages:
- stage: Deploy
  displayName: "Deploy Stage"
  jobs:
  - job