trigger: none

resources:
  pipelines:
  - pipeline: validation
    source: Nabanita-Sahu.Validate
    project: PipelineDemo
    branch: main
    trigger: true

pool:
  name: DevOpsPracticePool

stages:
- stage: Deploy
  displayName: "Deploy Stage"
  jobs:
  - job: DeployJob
    displayName: "Deploy Application"
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: "Download build artifacts"
        inputs:
          source: specific
          project: PipelineDemo
          pipeline: validation
          runVersion: latest
          artifact: drop
          path: $(Pipeline.Workspace)/drop

      - script: |
          echo "Starting deployment..."

          echo "Pipeline.Workspace = $(Pipeline.Workspace)"
          echo "Listing workspace contents:"
          ls -la "$(Pipeline.Workspace)"

          echo "Listing drop folder contents (if exists):"
          ls -la "$(Pipeline.Workspace)/drop" || echo "Drop folder not found yet"

          ARTIFACT_PATH="$(Pipeline.Workspace)/drop"

          echo "Checking for artifact at: $ARTIFACT_PATH"

          if [ -d "$ARTIFACT_PATH" ]; then
              echo " Artifact 'drop' found at: $ARTIFACT_PATH"
              echo "Deploying application..."
          else
              echo " Artifact 'drop' not found. Deployment cannot continue."
              exit 1
          fi

          echo " Deployment step completed."
        displayName: "Deployment Step"