trigger: none   # Deployment should not run automatically on code push

resources:
  pipelines:
  - pipeline: validation
    source: Nabanita-Sahu.Validate   # ✅ Exact name of your validation pipeline
    trigger: none                    # ✅ Disable auto-trigger to avoid early execution

pool:
  name: DevOpsPracticePool

stages:
- stage: Deploy
  displayName: "Deploy Stage"
  jobs:
  - job: DeployJob
    displayName: "Deploy Application"
    steps:

    # ✅ Download artifact from specific run ID (build #15)
    - task: DownloadPipelineArtifact@2
      displayName: 'Download build artifacts'
      inputs:
        source: 'specific'
        project: $(System.TeamProject)
        pipeline: <pipeline ID>           # Replace with numeric ID of Nabanita-Sahu.Validate
        runVersion: 'specific'
        runId: 15                         # ✅ Use actual run ID from successful validation run
        artifact: 'drop'
        path: '$(Pipeline.Workspace)'

    # ✅ Deployment placeholder
    - script: |
        echo "Deploying application..."
        echo "Artifacts downloaded to $(Pipeline.Workspace)"
      displayName: "Deployment Step"