trigger: none

resources:
  pipelines:
  - pipeline: validation
    source: Nabanita-Sahu.Validate
    project: PipelineDemo
    branch: main
    trigger: true

pool:
  name: DevOpsPracticePool

stages:
- stage: Deploy
  displayName: "Deploy Stage"
  jobs:
  - job: DeployJob
    displayName: "Deploy Application"
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: "Download build artifacts"
        inputs:
          source: specific
          project: PipelineDemo
          pipeline: validation                 # MUST match alias
          runVersion: latestFromTriggeringPipeline
          artifact: drop
          path: $(Pipeline.Workspace)/drop  # Force artifact into /drop folder

      - script: |
          echo "Starting deployment..."

          set "ARTIFACT_PATH=$(Pipeline.Workspace)\drop"

          echo Checking for artifact at: %ARTIFACT_PATH%

          if exist "%ARTIFACT_PATH%" (
              echo Artifact 'drop' found at: %ARTIFACT_PATH%
              echo Deploying application...
          ) else (
              echo Artifact 'drop' not found. Skipping deployment.
              exit /b 1
          )

          echo Deployment step completed.
        displayName: "Deployment Step" 
        #added this fot Triggering CI/CD test
        #testing

