trigger: none

resources:
  pipelines:
  - pipeline: validation
    source: Nabanita-Sahu.Validate
    trigger: true

pool:
  name: DevOpsPracticePool

stages:                     # ✅ This is the missing block
- stage: Deploy
  displayName: "Deploy Stage"
  jobs:
  - job: DeployJob
    displayName: "Deploy Application"
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download build artifacts'
      inputs:
        source: 'specific'
        project: $(System.TeamProject)
        pipeline: validation
        runVersion: 'latest'
        artifact: 'drop'
        path: '$(Pipeline.Workspace)'

    - script: |
        echo "Deploying application..."
        echo "Artifacts downloaded to $(Pipeline.Workspace)"
      displayName: "Deployment Step"