name: Build and Test C# Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT_PREFIX: 'Practice'
      FUNCTION_APP_PROJECT_NAME: 'Practice.Functions'
      FUNCTION_APP_WORKING_DIRECTORY: './src/function-apps'
      FUNCTION_APP_TEST_PROJECT_NAME: 'Practice.Functions.Tests'
      FUNCTION_APP_TEST_DIRECTORY: './src/tests'

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build
        run: dotnet build --no-restore

      # Step 5: Run tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # Step 6: Artifact upload step
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
        name: test-results
        path: ./TestResults/